[package]
name = "indexer"
version = "0.1.0"
edition = "2024"

[dependencies]
markdown = "1.0.0"
log = "0.4.27"
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }
postcard = { version = "1.1.2", features = ["use-std"] }
